export interface Integration {
  advertiserName: string
  advertiserId: string
  salesManager: string
  operationManager: string
  isConnected: boolean
  cpsAccountId: string | null
  connectedAt: string | null
  disconnectedAt: string | null
}

export const dummyIntegrations: Integration[] = [
  {
    advertiserName: "메드업_포스티",
    advertiserId: "posty",
    salesManager: "정재윤",
    operationManager: "김민수",
    isConnected: true,
    cpsAccountId: "lotocps",
    connectedAt: "2025-01-15",
    disconnectedAt: null,
  },
  {
    advertiserName: "BAT_LG전자",
    advertiserId: "LGECOM",
    salesManager: "이영희",
    operationManager: "박지훈",
    isConnected: true,
    cpsAccountId: "ilikecps",
    connectedAt: "2025-01-10",
    disconnectedAt: null,
  },
  {
    advertiserName: "DMC미디어_한국어드비시스템즈",
    advertiserId: "dmcmedia08",
    salesManager: "정재윤",
    operationManager: "최수진",
    isConnected: true,
    cpsAccountId: "keywordbridgecps",
    connectedAt: "2025-01-08",
    disconnectedAt: null,
  },
  {
    advertiserName: "도트림_네오위즈",
    advertiserId: "neowiz_mkt001",
    salesManager: "김철수",
    operationManager: "김민수",
    isConnected: true,
    cpsAccountId: "neowizcps",
    connectedAt: "2025-01-05",
    disconnectedAt: null,
  },
  {
    advertiserName: "PTBWA_알리익스프레스",
    advertiserId: "aliexpress",
    salesManager: "이영희",
    operationManager: "박지훈",
    isConnected: true,
    cpsAccountId: "alicps",
    connectedAt: "2024-12-28",
    disconnectedAt: null,
  },
  {
    advertiserName: "직_라이킷",
    advertiserId: "likeeat1",
    salesManager: "정재윤",
    operationManager: "최수진",
    isConnected: true,
    cpsAccountId: "likecps",
    connectedAt: "2024-12-20",
    disconnectedAt: null,
  },
  {
    advertiserName: "허브넷_시원스쿨",
    advertiserId: "siwon12",
    salesManager: "김철수",
    operationManager: "김민수",
    isConnected: true,
    cpsAccountId: "siwoncps",
    connectedAt: "2024-12-15",
    disconnectedAt: null,
  },
  {
    advertiserName: "모비데이즈_KB차차차",
    advertiserId: "kbchachachaapp",
    salesManager: "이영희",
    operationManager: "박지훈",
    isConnected: true,
    cpsAccountId: "kbcps",
    connectedAt: "2024-12-10",
    disconnectedAt: null,
  },
  {
    advertiserName: "엠포스_GS홈쇼핑",
    advertiserId: "gsshop_main",
    salesManager: "정재윤",
    operationManager: "최수진",
    isConnected: true,
    cpsAccountId: "gsshopcps",
    connectedAt: "2024-12-05",
    disconnectedAt: null,
  },
  {
    advertiserName: "크리테오_무신사",
    advertiserId: "musinsa_kr",
    salesManager: "김철수",
    operationManager: "김민수",
    isConnected: true,
    cpsAccountId: "musinsacps",
    connectedAt: "2024-11-28",
    disconnectedAt: null,
  },
  {
    advertiserName: "아이지에이웍스_29CM",
    advertiserId: "cm29_app",
    salesManager: "이영희",
    operationManager: "박지훈",
    isConnected: true,
    cpsAccountId: "29cmcps",
    connectedAt: "2024-11-20",
    disconnectedAt: null,
  },
  {
    advertiserName: "디지털다임_현대백화점",
    advertiserId: "hyundai_dept",
    salesManager: "정재윤",
    operationManager: "최수진",
    isConnected: true,
    cpsAccountId: "hyundaicps",
    connectedAt: "2024-11-15",
    disconnectedAt: null,
  },
]

export interface Account {
  id: string
  name: string
  salesManager: string
  operationManager: string
  hasScript: boolean
}

export const parentAccounts: Account[] = [
  {
    id: "bnrmall",
    name: "비욘드콘택트_더화이트컴퍼니",
    salesManager: "조용현",
    operationManager: "김지훈",
    hasScript: true,
  },
  { id: "gmarket1", name: "엠포스_지마켓", salesManager: "정재윤", operationManager: "김민수", hasScript: true },
  { id: "gmarket2", name: "곰플레이어 지마켓", salesManager: "이영희", operationManager: "박지훈", hasScript: true },
  { id: "gmarket3", name: "코리아닷컴 지마켓2", salesManager: "김철수", operationManager: "최수진", hasScript: false },
  { id: "auction_main", name: "옥션_메인", salesManager: "정재윤", operationManager: "김민수", hasScript: true },
  { id: "11st_shop", name: "11번가_쇼핑", salesManager: "이영희", operationManager: "박지훈", hasScript: true },
  { id: "coupang", name: "쿠팡코리아", salesManager: "김철수", operationManager: "최수진", hasScript: true },
  { id: "wemakeprice", name: "위메프", salesManager: "정재윤", operationManager: "김민수", hasScript: false },
  { id: "linkprice", name: "링크프라이스", salesManager: "이영희", operationManager: "박지훈", hasScript: true },
]

export const cpsAccounts: Account[] = [
  { id: "lotocps", name: "로토CPS_연동", salesManager: "정재윤", operationManager: "김민수", hasScript: true },
  { id: "gmarketcps", name: "지마켓CPS", salesManager: "이영희", operationManager: "박지훈", hasScript: true },
  {
    id: "auction_maincps",
    name: "옥션_메인cps",
    salesManager: "김철수",
    operationManager: "최수진",
    hasScript: true,
  },
  { id: "shopcps", name: "쇼핑cps_메인", salesManager: "정재윤", operationManager: "김민수", hasScript: false },
  { id: "coupangcps", name: "쿠팡cps", salesManager: "이영희", operationManager: "박지훈", hasScript: true },
  { id: "linkpricecps", name: "링크프라이스cps", salesManager: "김철수", operationManager: "최수진", hasScript: true },
  { id: "wemakepricecps", name: "위메프cps", salesManager: "정재윤", operationManager: "김민수", hasScript: true },
  { id: "affiliatecps", name: "제휴cps_광고", salesManager: "이영희", operationManager: "박지훈", hasScript: false },
]

export interface User {
  id: string
  joinedAt: string
  status: "중지" | "라이브"
  type: "광고주" | "대행사"
  salesManager: string
  companyName: string
  contactPerson: string
  contactPhone: string
  agency: string
  userId: string
  category: string
  gender: string
  ageRange: string
  url: string
  scriptStatus: "미삽입" | "삽입" | ""
}

export const dummyUsers: User[] = [
  {
    id: "1",
    joinedAt: "2025-12-29 17:37:57",
    status: "중지",
    type: "광고주",
    salesManager: "",
    companyName: "직_정원e샵CPS",
    contactPerson: "황호성",
    contactPhone: "010-3193-0783",
    agency: "",
    userId: "jungonecps",
    category: "",
    gender: "",
    ageRange: "",
    url: "",
    scriptStatus: "미삽입",
  },
  {
    id: "2",
    joinedAt: "2025-12-29 17:22:31",
    status: "중지",
    type: "대행사",
    salesManager: "",
    companyName: "하나애드아이엠씨",
    contactPerson: "문소정",
    contactPhone: "010-5136-5438",
    agency: "",
    userId: "msjthwjd00",
    category: "",
    gender: "",
    ageRange: "",
    url: "",
    scriptStatus: "미삽입",
  },
  {
    id: "3",
    joinedAt: "2025-12-29 17:10:10",
    status: "중지",
    type: "광고주",
    salesManager: "",
    companyName: "직_리퍼연구소cps",
    contactPerson: "황호성",
    contactPhone: "010-3193-0783",
    agency: "",
    userId: "refurlabcps",
    category: "",
    gender: "",
    ageRange: "",
    url: "",
    scriptStatus: "미삽입",
  },
  {
    id: "4",
    joinedAt: "2025-12-29 17:07:22",
    status: "중지",
    type: "광고주",
    salesManager: "",
    companyName: "직_교복몰CPS",
    contactPerson: "황호성",
    contactPhone: "010-3193-0783",
    agency: "",
    userId: "gyobokcps",
    category: "",
    gender: "",
    ageRange: "",
    url: "",
    scriptStatus: "미삽입",
  },
  {
    id: "5",
    joinedAt: "2025-12-29 15:28:47",
    status: "중지",
    type: "광고주",
    salesManager: "송정호",
    companyName: "미래아이엔씨_성용수산",
    contactPerson: "김규원",
    contactPhone: "010-6645-4555",
    agency: "미래아이엔씨_마스터",
    userId: "yp4555",
    category: "농수산식품종합",
    gender: "남자,여자",
    ageRange: "36세~44세",
    url: "sysusan.co.kr",
    scriptStatus: "미삽입",
  },
  {
    id: "6",
    joinedAt: "2025-12-29 14:46:37",
    status: "중지",
    type: "광고주",
    salesManager: "김승연",
    companyName: "프로그레스미디어_YNM",
    contactPerson: "강현주",
    contactPhone: "010-2213-2946",
    agency: "프로그레스미디어_마스터",
    userId: "pink001023",
    category: "화징품",
    gender: "여자",
    ageRange: "25세~27세",
    url: "ynmcosmetic.co.kr",
    scriptStatus: "미삽입",
  },
  {
    id: "7",
    joinedAt: "2025-12-29 14:32:27",
    status: "중지",
    type: "광고주",
    salesManager: "",
    companyName: "웰컴드링크",
    contactPerson: "김정진",
    contactPhone: "010-7653-7367",
    agency: "",
    userId: "welcome_drink",
    category: "",
    gender: "",
    ageRange: "",
    url: "",
    scriptStatus: "미삽입",
  },
  {
    id: "8",
    joinedAt: "2025-12-29 13:46:08",
    status: "중지",
    type: "광고주",
    salesManager: "",
    companyName: "화해",
    contactPerson: "박가희",
    contactPhone: "010-8478-1038",
    agency: "",
    userId: "hwahae",
    category: "화징품",
    gender: "여자",
    ageRange: "25세~27세",
    url: "hwahae.co.kr/",
    scriptStatus: "미삽입",
  },
  {
    id: "9",
    joinedAt: "2025-12-29 13:28:37",
    status: "중지",
    type: "광고주",
    salesManager: "서현이",
    companyName: "직_하나인더스트리",
    contactPerson: "정원영",
    contactPhone: "010-4457-0905",
    agency: "",
    userId: "hana-industry",
    category: "가전",
    gender: "여자",
    ageRange: "36세~44세",
    url: "blaupunkt-life.kr",
    scriptStatus: "미삽입",
  },
  {
    id: "10",
    joinedAt: "2025-12-26 18:27:05",
    status: "중지",
    type: "광고주",
    salesManager: "서현이",
    companyName: "포엘에이디_디엘성형외과",
    contactPerson: "강수연",
    contactPhone: "010-2615-1253",
    agency: "포엘에이디_마스터",
    userId: "dlps1101",
    category: "성형외과",
    gender: "남자,여자",
    ageRange: "28세~35세",
    url: "dlprs.com",
    scriptStatus: "미삽입",
  },
  {
    id: "11",
    joinedAt: "2025-12-26 14:47:09",
    status: "중지",
    type: "광고주",
    salesManager: "서현이",
    companyName: "티와이마케팅_사과당",
    contactPerson: "엄태영",
    contactPhone: "010-7700-7480",
    agency: "티와이마케팅_마스터",
    userId: "sagwadangcafe",
    category: "창업",
    gender: "남자,여자",
    ageRange: "36세~44세",
    url: "appledangcafe.co.kr",
    scriptStatus: "미삽입",
  },
  {
    id: "12",
    joinedAt: "2025-12-26 11:04:03",
    status: "라이브",
    type: "광고주",
    salesManager: "강병우",
    companyName: "AMPM_아포테(프로모션)",
    contactPerson: "이예진",
    contactPhone: "010-9706-2085",
    agency: "ampm_마스터",
    userId: "apothe2",
    category: "프로모션",
    gender: "여자",
    ageRange: "25세~27세",
    url: "apothe.co.kr1",
    scriptStatus: "",
  },
  {
    id: "13",
    joinedAt: "2025-12-26 10:44:00",
    status: "중지",
    type: "광고주",
    salesManager: "",
    companyName: "상상플러스",
    contactPerson: "이현주",
    contactPhone: "010-2473-5056",
    agency: "",
    userId: "ohjoojoo",
    category: "",
    gender: "",
    ageRange: "",
    url: "",
    scriptStatus: "",
  },
]
